name: 'Compare Performance'
description: 'Greet someone and record the time'
inputs:
  input-file-name: 
    description: 'The name of file of result of tests(K6s)'
    required: true

  output-file-name:
    description: 'The name of file to save in local machine'
    required: false

  desviation-error:
    description: 'The desviation in percentage of acceptable errors'
    required: false
    default: '0.1'

  desviation-latency:
    description: 'The desviation in percentage of acceptable latency'
    required: false
    default: '0.1'

  base-latency:
    description: 'The base in ms(milliseconds) of acceptable latency'
    required: false
    default: '{"avg": 80, "max": 100, "min": 70, "P90": 80, "P95": 90}'

outputs:
  message:
    description: 'The text to send to the pr'


runs:
  using: 'node20'
  main: 'dist/index.js'
